version: '3.9'

volumes:
  database_cities:

services:
  database_user_repository:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=user
      - POSTGRES_DB=users
    volumes:
      - database_cities:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5434}:5432