server:
  port: 8084
jwt:
  secret: secretkey
  token:
    validity: 180000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: lb://city-service
          predicates:
            - Path=/users/**
        - id: cities
          uri: lb://city-service
          predicates:
            - Path=/cities/**
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**