version: '3.9'

volumes:
  database_cities:

services:
  database_cities:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=city
      - POSTGRES_DB=cities
    volumes:
      - database_cities:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432